version: 2.1
jobs:
  test_php_7:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - run: composer install
      - run: vendor/bin/phpunit
  test_php_8:
    docker:
      - image: cimg/php:8.2
    steps:
      - checkout
      - run: composer install
      - run: vendor/bin/phpunit

workflows:
  tests:
    jobs:
      - test_php_8
      - test_php_7
